# Common stuff

theme:
  name: 'material'
  palette:
    primary: 'Teal'
    accent: 'Teal'
  feature:
    tabs: true
markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
use_directory_urls: false
extra:
  search:
    tokenizer: '[\s\-\.]+'
  social:
    - type: 'github'
      link: 'https://github.com/openlilylib'
    - type: 'wordpress'
      link: 'http://lilypondblog.org'
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized
repo_url: https://github.com/uliska/lilyponds-scheme/
site_dir: '../site/internals'
edit_uri: edit/master/internals/docs
site_name: LilyPond's Scheme Internals
nav:
  - "LilyPond's Scheme â¬ˆ": ../index.html
  - 'Advanced Interaction With Scheme':
    - 'Intro': 'index.md'
    - 'Built-in Scheme Functions': 'built-in/README.md'
    - 'Overriding Stencils]': 'overriding-stencils.md'
    - 'Scheme Engravers': 'engravers/README.md'
    - 'Scheme Representation of Music': 'scheme-music/README.md'
  - 'License': 'license.md'
